services:
  app:
    image: todo-testing
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: todo-testing
