version: "3.8"

services:
  nginx:
    image: nginx:1.20.1
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 5000:80
    container_name: reverse-proxy
    depends_on:
      - frontend
      - backend

  frontend:
    image: frontend-prod
    restart: always
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=/api
    container_name: frontend-prod

  backend:
    image: backend-prod
    restart: always
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:complex-example@mongo:27017/the_database
      - PORT=3001
    depends_on:
      - mongo
      - redis
    container_name: backend-prod

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: mongo

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis

volumes:
  mongo_data:
